backend:
  name: git-gateway
  branch: master
media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: hoyosartimagecloud
    api_key: 712995591669847
collections:
  - name: 'artwork'
    label: 'Artwork'
    format: 'json'
    folder: 'assets/content/artwork'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Height', name: 'height', widget: 'string' }
      - { label: 'Width', name: 'width', widget: 'string' }
      - { label: 'Medium', name: 'medium', widget: 'string' }
      - { label: 'Number of Frames', name: 'numberOfFrames', widget: 'number', default: 1 }
      - { label: 'Order', name: 'galleryOrder', widget: 'number', default: 50 }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Date (used for order)', name: 'date', widget: 'datetime'}
      - { label: 'Gallery',
          name: 'gallery',
          widget: 'select',
          multiple: true,
          options: ['Home', 'Abstracts', 'Figurative Abstract', 'Contemporary', 'Surreal']
        }

